### ISSUE TITLE
Can you please release this mod on cities-mods.com

### ISSUE THREAD

**Issue by TylerAustin7** [DominicMaas/Tango#260]
Can you please release this mod on https://cities-mods.com/xlex/categories/cities-skyline.53/ so others users can enjoy it as well

**Comment by apflu** [comment]
says my ip address banned, is this not a open forum at all?
Edit: a phishing site?

**Comment by bolandnick18** [comment]
Yes is a open forum can I get your IP address so I can removed it

**Comment by TylerAustin7** [comment]
It now fixed can you please tried again

**Comment by DominicMaas** [comment]
Ideally I want to keep the metadata for this mod quite centralized. At the moment we have the Steam Listing, alongside website and GitHub which I'm alright with.
