### ISSUE TITLE
Imcompatible w/ TM:PE Stable

### ISSUE THREAD

**Issue by VictorXcraft** [DominicMaas/Tango#262]
**Describe the bug**
Error message shown when try to use TM:PE.

**To Reproduce**
1. Go to 'Content Manager'
2. Click on 'TM:PE Stable'
3. See error
![image](https://user-images.githubusercontent.com/81340759/151022297-c075235f-0815-4ec3-9d64-fc7d72b08b44.png)

**Expected behavior**
Nothing happened when it turns on

**Screenshots**
![image](https://user-images.githubusercontent.com/81340759/151022297-c075235f-0815-4ec3-9d64-fc7d72b08b44.png)

**Active DLCs**
All DLCs.

**Active mods**
81 Tiles, Multiplayer Mod, Harmony, Move It, Network Extensions 3

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: newest
- Game version: newest

**Comment by vinnn-90** [comment]
Would be amazing if this would work with CSM!
Anyone knows if older versions of TMPE used to work with CSM?

**Comment by JerryPLayz** [comment]
> Would be amazing if this would work with CSM! Anyone knows if older versions of TMPE used to work with CSM?

Due to the way CSM works, a specific compatibility mod will need to be made to sync TM:PE with CSM. (As CSM currently has to sync elements specifically)

**Comment by kaenganxt** [comment]
Continued in #289
