### ISSUE TITLE
Cities Skylines 2022-01-25 (Version with Airport DLC) causes issues

### ISSUE THREAD

**Issue by Gussoh** [DominicMaas/Tango#263]
**Describe the bug**
Steam installed the new update containing airports DLC and now there are issues when even doing simple things.

We also had parklife DLC. I can't be entirely sure it is not causing it, but there seems to be other people reporting the same issue in the Steam community forum.

**To Reproduce**
1. start multiplayer game
2. have someone join
3. have the joined client build long roads across the land

**Expected behavior**
Both clients will have nice roads across the land

**What actually happens**
Ravines and canals are introduced across the map on the server side

**Screenshots**
![ravines](https://user-images.githubusercontent.com/8473085/151066587-8f6da4c2-6132-4d1c-9a3d-02bc7d20b6ad.jpg)

**Active DLCs**
Parklife

**Active mods**
-

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 5 Apr, 2021 @ 11:37pm
- Game version: 1.14.0-f4

**Additional context**
Steam community forum post:
https://steamcommunity.com/workshop/filedetails/discussion/1558438291/3194742665190255670/

**Comment by lastmetroid** [comment]
Same issue since today's update, sadly random corruptions happening all over the map while building.

**Comment by Gussoh** [comment]
Issue seems to be solved with the recent update
