### ISSUE TITLE
Airport Updates

### ISSUE THREAD

**Issue by aggelosd** [DominicMaas/Tango#264]
**Describe the bug**
Sync problems, random holes in the ground, zoning and building not appearing
**To Reproduce**

**Expected behavior**

**Screenshots**

**Active DLCs**
Please add a list of your enabled DLCs here.

**Active mods**
Please add a list of your installed and enabled mods here.

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 
- Game version: 

**Additional context**

**Comment by Gussoh** [comment]
Duplicate of #263
