### ISSUE TITLE
Airport DLC issues

### ISSUE THREAD

**Issue by MagixBaracuda** [DominicMaas/Tango#265]
**Describe the bug**
You cannot place a road without a terrain bug. We try to de-activate all workshop mods regarding road that can maybe create the problem, play a different map, change the host... it is broken by the DLC.

**To Reproduce**
- Create a multiplayer
- Join in
- Place road... bug occurs

**Screenshots**
<img src="https://i.ibb.co/VY4j8TF/Capture.png" alt="Capture" border="0">

**Active DLCs**
All DLCs, except Natural Disasters

**Active mods**
Fine Road Tool
Auto Bulldoze
Precision Engineering
customize Bus livery (TPG addon)

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Game version: last version released with Airport DLC on January 25 2022.

Hope you will solve this bug, because your MOD is AMAZING!

**Comment by adamlibby** [comment]
I'm experiencing the same issue. With no other mods installed, the roads where glitching through the terrain. It looked like the roads were snapping to the world origin. Possibly a parsing bug?

**Comment by Gussoh** [comment]
Duplicate of #263

**Comment by SSSKrut** [comment]
I will add something, although I am not a developer. Roads are superimposed on each other when improving, and several levels can lie in one road cell. Another bug of roads occurs with other communications - water pipes and subway tunnels.

**Comment by lastmetroid** [comment]
Does the new build 2201.180  fix this?

**Comment by elijah-h-lgtm** [comment]
> Does the new build 2201.180 fix this?

as far as I have tested yes.

**Comment by Greymagic27** [comment]
As mentioned, this is a duplicate of #263.
