### ISSUE TITLE
Create server bin for deployment on external server

### ISSUE THREAD

**Issue by KaymeKaydex** [DominicMaas/Tango#278]
There is very slow and busy to create network by smth like hamachi
Lets do the release with binary file to deploy the server on some external pc

**Comment by DominicMaas** [comment]
Are you talking about something like #67 ?

**Comment by KaymeKaydex** [comment]
> Are you talking about something like #67 ?

yep, there is the same issue

**Comment by DominicMaas** [comment]
Cool, I'll close this as a duplicate, feel free to upvote the other issue.

Duplicate of #67
