### ISSUE TITLE
Rework Connection Error Messages (Port Forwarding)

### ISSUE THREAD

**Issue by DominicMaas** [DominicMaas/Tango#295]
At the moment the connection error messages related to port forwarding, and checking if a port is forwarded are confusing users that are using tools like Hamachi, we probably need to reword these messages to act like suggestions? Or mention if using a Hamachi like service you don't need to worry about this.

**Comment by kaenganxt** [comment]
Fixed by #298

- Most issues should be solved by the new NAT hole punching mechanism.
- If it still doesn't work, additional troubleshooting information is displayed.
- The mod tries to detect Hamachi to improve the displayed messages if it is available.
