### ISSUE TITLE
can't see my cities

### ISSUE THREAD

**Issue by SpearThrower** [DominicMaas/Tango#304]
**Describe the bug**
I can't see any roads, buildings, props, city edge lines(which classifies my land and not). and when I try to build or place any road, prob, building, water, anything error "Object reference not set to an instance of an object" appears. This breaks out both in new game and loaded game. and also even when I managed my mods and assets and checking imcompatibility, omissions again happened.

**To Reproduce**

**Expected behavior**
it seems there are lands with grasses but I can' t its own graphics when I close look at. I can't see any boundary of my territory, no roads, buildings. When I load my cities not new, my buildings are seen with light wall which you can see in the kind of functional tab(water, medical etc). but can't see actual appearance.

**Screenshots**
![image](https://user-images.githubusercontent.com/127949806/225325088-05b6994d-9e67-4261-8198-79f649e4a83c.png)
![image](https://user-images.githubusercontent.com/127949806/225329723-95cc172b-c651-4298-98a5-bb70437c9009.png)
![image](https://user-images.githubusercontent.com/127949806/225329795-df749e20-9d26-42ec-8a3f-d41bca892b94.png)
![image](https://user-images.githubusercontent.com/127949806/225329893-44ffde2c-7644-404b-b819-ee2992afe732.png)
![image](https://user-images.githubusercontent.com/127949806/225331937-7377fcee-ee7a-40ee-a81c-9077fb69c6d2.png)

**Active DLCs**
Carols, Candles and Candy
Korean language
Match Day
Pearls From the East
Mass Transit
Industries
Snowfall
After Dark
Green Cities
Natural Disasters
Parklife
Campus

**Active mods**
* 1794015399 Render It!
* 1758376843 Network Skins
* 453956891 Mesh Info 1.3.3
* 2025147082 Realistic Population 2 2.2.2
* 2414618415 Adaptive Networks 3.17
* 2133885971 Find It! 2.9.3
* 2027161563 Lifecycle Rebalance Revisited 1.6.6
* 2893645082 Outside Traffic Balancer
* 1591417160 Hide It!
* 2607683510 Real Train Sound
* 818641631 Ambient Sounds Tuner
* 780720853 Vehicle Effects 1.9.4
* 2862881785 Network Anarchy 3.2
* 2907304748 보다 사실적인 사운드 FX 팩(1.0.0)
* 2902507619 Extra Vehicle Effects 0.4
* 2448994345 Yet Another Toolbar 1.1.6-2
* 2472062376 Node Controller Renewal 3.4.0.1
* 2140418403 Intersection Marking Tool 1.13.1
* 2911178252 Rebalanced Industries Revisited Beta 0.7.0
* 2741726428 Play It!
* 515489008 Extra Train Station Tracks
* 2881031511 Compatibility Report v2.3.2
* 2862121823 81 tiles 2 1.0.1
* 2864913941 Surface Painter temporary fix
* 2696146766 Prop Anarchy 0.7.7
* 2527486462 Tree Anarchy 1.3.6
* 2483920668 Fog Controller
* 2805340879 Transfer Controller 0.7.8
* 2862992091 Elevated Stops Enabler Revisited 2.0.0.3
* 2862940316 Extra Landscaping Tools
* 2858654134 Traffic Volume
* 2016920607 RICO Revisited 2.5.3
* 2041457644 Patch Loader Mod v2.2.0
* 2862973068 Advanced Stop Selection Revisited 2.0.0.3
* 2255219025 Unified UI 2.2
* 1627986403 Bulldoze It!
* 1548831935 Advanced Vehicle Options 1.9.10
* 816260433 Metro Overhaul
* 412149127 Font Selector
* (local) Unlimited Soil
* 2040656402 Harmony 2.2.2-0
* 812125426 Network Extensions 2
* 1420955187 Real Time
* 2696146165 Extended Managers 1.0.3
* 2858591409 Loading Screen Mod Revisited 1.1.3
* 2594569657 Parking Lot Snapping
* 1619685021 Move It 2.9.11
* 1886877404 Custom Effect Loader
* 2101551127 Repaint 1.7.3
* 2455665392 EYM: Enlighten Your Mouse 1.2
* 2882769913 Vehicle Selector 1.4.1.2
* 2778750497 ACME 0.6.3
* 2764243667 First Person Camera v2.1
* 1637663252 TM:PE 11.7.3.1 STABLE
* 2560782729 Network Multitool 1.3.3.4
(local) Hard Mode
(local) Unlimited Oil And Ore
(local) Unlimited Money
(local) Unlock All
1522785644 Infinite Demand Mod
1804882663 Monitor It!
785528371 Cinematic Camera Extended 0.5.1
2105755179 FPS Booster 0.8.3

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: almost new version
- Game version: currently new version maybe it's 1.14.1

**Additional context**
[AdaptiveRoads.log](https://github.com/CitiesSkylinesMultiplayer/CSM/files/10980522/AdaptiveRoads.log)
[CompatibilityReport.log](https://github.com/CitiesSkylinesMultiplayer/CSM/files/10980524/CompatibilityReport.log)
[FPS_Booster_AutoPatcher.log](https://github.com/CitiesSkylinesMultiplayer/CSM/files/10980542/FPS_Booster_AutoPatcher.log)
[FPS_Booster.log](https://github.com/CitiesSkylinesMultiplayer/CSM/files/10980545/FPS_Booster.log)
[PatchLoader.log](https://github.com/CitiesSkylinesMu
[output_log.txt](https://github.com/CitiesSkylinesMultiplayer/CSM/files/10980553/output_log.txt)
ltiplayer/CSM/files/10980547/PatchLoader.log)

**Comment by kaenganxt** [comment]
After looking at your logs I don't see any appearance of CSM. Are you sure this report is related to playing in multiplayer with our mod?

Besides that, the log shows two exceptions from the mods NetworkMultitool and 81 Tiles 2. You could try to remove them and see if it helps. You have a lot of different mods installed, which could all possibly interfere with each other. As long as the issue is not caused by CSM (=the game works without CSM, but doesn't, when CSM is installed and enabled), I'm afraid I can't help you here.

**Comment by SpearThrower** [comment]
> After looking at your logs I don't see any appearance of CSM. Are you sure this report is related to playing in multiplayer with our mod?
> 
> Besides that, the log shows two exceptions from the mods NetworkMultitool and 81 Tiles 2. You could try to remove them and see if it helps. You have a lot of different mods installed, which could all possibly interfere with each other. As long as the issue is not caused by CSM (=the game works without CSM, but doesn't, when CSM is installed and enabled), I'm afraid I can't help you here.
