### ISSUE TITLE
Text corruption and game hangs when attempting to start multiplayer

### ISSUE THREAD

**Issue by MarauderIIC** [DominicMaas/Tango#314]
**Describe the bug**
Loading an existing save and clicking "Multiplayer" to start a server results in image corruption. Game hangs and does not respond to alt+f4.

Same happens when clicking Multiplayer from a new game.

**To Reproduce**
1. Start Cities Skylines via Play from the launcher
2. Select Continue Game from the main menu
3. Press Escape, and select Multiplayer
4. Text corrupts and game hangs
----
1. Start Cities Skylines via Play from the launcher
2. Select New Game from the main menu
3. Press Escape, and select Multiplayer
4. Text corrupts and game hangs

**Expected behavior**
Expected create server dialog to appear as before 1.17.0-f3

**Screenshots**
After hitting escape and clicking Multiplayer after loading a new save,
![image](https://github.com/CitiesSkylinesMultiplayer/CSM/assets/1060259/eea9280d-7820-4dc8-8bf9-587b4055c90e)

**Active DLCs**
Industries
Mass Transit
Sunset Harbor

**Active mods**
Harmony 2.2-0 (Mod Dependency)

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 2304.267.0.0
- Game version: 1.17.0-f3

**Additional context**
Did not happen on game version prior to 1.17.0-f3.

**Comment by kaenganxt** [comment]
This issue once appeared due to a new Cities update but was fixed quickly on our side. If this issue still happens to you, make sure you have the latest version of CSM installed by either installing it from the Steam Workshop or following the instructions on https://citiesskylinesmultiplayer.com/
