### ISSUE TITLE
Main UI gamebar gone + game screen froze.

### ISSUE THREAD

**Issue by DeManHemZelfe** [DominicMaas/Tango#316]
**Describe the bug**
Main UI bar is gone and the game  screen froze but i get some sound notifications from the game. So it likes that the game screen froze but the game didn't

**To Reproduce**
1. Go to the main menu
2. Click on new game and start a random map
3. See that the UI bar is gone

**Expected behavior**
That the main ui gamebar doesn't vanish and the game don't freeze

**Screenshots**
![image](https://github.com/CitiesSkylinesMultiplayer/CSM/assets/42802392/27c9d8f3-82ab-4ea8-a554-d0e82b4f08b0)

**Active DLCs**
All dlc are inactive

**Active mods**
All mods are inactive instead of the multiplayer mod

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 
- Game version:  latest version

**Additional context**
No

**Comment by kaenganxt** [comment]
This issue once appeared due to a new Cities update but was fixed quickly on our side. If this issue still happens to you, make sure you have the latest version of CSM installed by either installing it from the Steam Workshop or following the instructions on https://citiesskylinesmultiplayer.com
