### ISSUE TITLE
Error: No IUserMod implementation. Every mod must implement IUserMod

### ISSUE THREAD

**Issue by mykhailo-qdxp** [DominicMaas/Tango#319]
Error: No IUserMod implementation. Every mod must implement IUserMod

**Steps to reproduce the behavior:**
On game startup

**Screenshots**
![image](https://github.com/CitiesSkylinesMultiplayer/CSM/assets/96002073/28470bec-097e-4558-9ed0-a76798012634)

**Active DLCs**
All

**Active mods**
No active mods

**Versions**
Type /version into the in-game chat and paste the version numbers here:
- Mod version: 2305.270
- Game version: 1.17.0-f3

**Comment by kaenganxt** [comment]
This error message indicates that you didn't install the mod correctly. Try to reinstall it either from the Steam Workshop or using the instructions on https://citiesskylinesmultiplayer.com
If you need further help, join our Discord: https://discord.gg/RjACPhd
