### ISSUE TITLE
Adding Districts prevents all client changes pushing to server

### ISSUE THREAD

**Issue by flaktivated** [DominicMaas/Tango#320]
**Describe the bug:**
When the clients try to click on districts they receive an error and then the game crashes.
![image](https://github.com/CitiesSkylinesMultiplayer/CSM/assets/13980017/60b07eb4-6aab-4d77-9890-51068ca10178)

When the server creates a district all changes the client makes are not synced to the server. I.E. they can't build roads, buildings, pipes etc.

**Expected Behaviour:**
Clients can place and update districts and keep other changes in sync.
When a server places a district other sync functionality is not impacted.

**How to Reproduce:**
- Start a new Map
- Grow city until districts are available
- Place a district as a client or server

**Active DLC:** None
**Active Mods:** Harmony and CSM
**Mod Version:** 2305.270.0.0
**Game Version:** 1.17.0-f3

**Comment by kaenganxt** [comment]
Thanks for your report. With the information provided it is not really possible to reproduce your issue. It is definitely not happening every time when a district is created, as it works fine for many other players.
For us to be able to fix your issue, please provide more details on what exactly you and the other player are doing before the issue appears. Also, please enable debug logging in the CSM in-game settings before reproducing the error and attach the new log file afterwards.

The error message you are seeing would indicate a general problem with your CSM installation. But this should also mean that a connection to the server is not even possible. Maybe try to re-install CSM either from Steam Workshop or manually using the instructions provided on https://citiesskylinesmultiplayer.com

Closing this now as it is not reproducible for me, but please reopen if you want to provide further information.
